### ISSUE TITLE
Shorter syntax for declaring variables

### ISSUE THREAD

**Issue by Meai1** [jondgoodwin/cone#11]
Golang made a genius move by removing the 'var' in favor of :=
It makes all code shorter and more python-y
I propose that Cone makes the same move and does something like this:

`imm x = 5` becomes `x ::= 5` 
`mut x = 5` becomes `x := 5`

It's not just the amount of characters that is at play here. Reading a file from top to bottom is much easier when the name of variables is right there on the leftmost side. Consider this: imm and mut are in reality metadata for the compiler. Sure, it's useful to know this when reading code but the real information we usually want to know as programmers when we scan over some code visually with our eyes is not all this metadata stuff. It's the actual names of variables, functions, constructs. This syntax makes that scanning easier and faster for humans.

**Comment by jondgoodwin** [comment]
Thanks for the suggestion. In a language without permissions, I too see benefits to the := syntax. It is something I have thought about.

My largest concern here is that 'imm' and 'mut' are not the only permissions, opening up the need for variations on := for each of them, and then having people keep straight which is which. Because of this problem, it is more likely I would want to swap the permission and variable, sticking the permission after the colon and before any type, if present.

Making this change creates yet another challenge: parsing determinism. Variable declarations need to be statements and never expressions, and without some recognized leading token, the non-backtracking parser cannot enforce this. So, before making this design change, I would need to work out some other way to enforce this.

**Comment by cloudcalvin** [comment]
First off let me just say this language looks really great, nice job!

I was just about to make this suggestion as made by Meai1, except I would have had it the other way around, with `:=` for imm and `::=` for mut, since most will want immutability by default (having functional inclinations). 

My reasons for wanting the change are not tied to Go though, rather I wish for a language where the variable names are always first for readability sake (and a more declarative programming experience, see Red lang).
However, keywords after the variable name will also work for me. 

Sadly I do not have a solution for the parsing determinism issue, but I will point you to some interesting languages that might have solved the issue since they have variables without leading keywords:

moonscript: https://moonscript.org/
crystal: https://crystal-lang.org
red: https://www.red-lang.org/
jai: https://github.com/MichaelSDavid/Cupcake-Compiler/blob/master/modules-source/Basic/procedures.jai
pointless: https://ptls.dev/
agda? : https://agda.readthedocs.io

Either way, keep up the good work.

**Comment by jlmgtech** [comment]
I think this is a matter of personal preference.  As personal preference goes, I actually like `imm` and `mut` being on the leftmost side - it draws my eyes to variable declarations.  It actually really bugs me that go has both var AND the := operator.  Python suffers from the problem of not being able to declare a variable without assignment; golang supports unassigned declaration, but because of the infix declaration/assignment operator, there's now two ways to declare a variable.  I much prefer the simplicity of always having the declaration prefixed by a common keyword that IDEs know how to highlight.  Just my two cents.
