### ISSUE TITLE
Windows build instructions?

### ISSUE THREAD

**Issue by pluckyporcupine** [jondgoodwin/cone#16]
I'm a bit confused about how to build this properly (I don't use Visual Studio often). I currently have VS2019.

Here are the steps I took:

* Downloaded LLVM 7.0.1 Windows x64 binary.
* Set `LLVMDIR` environment variable to the LLVM 7.0.1 directory.
* Opened `Cone.vcxproj` and retargeted it for VS2019 and my current Windows SDK.
* File -> Add -> Existing project... -> `conestd.vcxproj` -> retargeted for VS2019 and my current Windows SDK.
* Set it to x64 instead of x86, but left it on Debug.
* Right-click -> Build Solution

I got this error:

`LINK : fatal error LNK1561: entry point must be defined`

It's the conestd project that's throwing this error. Am I not supposed to be using that one?

EDIT: I also see that I am going to have to build LLVM from source. There's no chance that it works with LLVM 9, is there? I've already got that one built from source.

If not, which flags would I need on Windows to ensure that it works with Cone?

**Comment by jondgoodwin** [comment]
You are right, on Windows you have to build LLVM from source. I do not know if it will work with LLVM 9, as I currently am still using LLVM 7 for my development work.  On Windows, I am building with x86, but I build 64-bit on Linux and it works there, so presumably x64 should work on Windows as well, I have just never tried.

conec is the compiler. conestd is just a tiny library in case you want some print functions that can be called by Cone programs.

Good luck and let me know if you need more help.

**Comment by pluckyporcupine** [comment]
I haven't gotten around to building LLVM just yet (will comment again when I do), but, as a side-note, are the examples of `extern` functions in the Cone Home repository still valid? I assume I just write those out and then link to the `.lib` in question?

**Comment by jondgoodwin** [comment]
yes. `extern` exists so that Cone may access functions / global variables implemented in some other C-ABI compatible library. I have not done much with these for the time-being, I use the `print` ones for the Cone playground (conesite repo) examples, just for testing purposes. And the samples in the conehome use extern to interface to SDL2/OpenGL and JS/WebGL functions. All right now for testing purposes as I fill out the base language first. Once it stabilizes, I will definitely begin filling out a more robust collection of libraries.

**Comment by pluckyporcupine** [comment]
Okay, I built LLVM 7.0.1 from source using the default settings because I wasn't sure what to use. I couldn't get it to build in Visual Studio because it refused to find the LLVM `include` folder, even when the `LLVMDIR` environment variable was set. I then changed it to `LLVM_DIR` and attempted to build using CMake. It also failed with the following error:

```LINK : fatal error LNK1181: cannot open input file 'LLVMAVRAsmParser.lib' [D:\Code\GitHub\cone\build\conec.vcxproj]```

Any idea what might be happening there? Are there any flags I was supposed to set for the LLVM build?

**Comment by jondgoodwin** [comment]
Sorry for the slow turnaround time, we are in different time zones (Australia here). Possibly we can have a faster turnaround time with Discord: https://discord.gg/8jArPHv

You are right that I had an extraneous include file in the Release side of the project file pointing to my E: folder. Thanks for spotting it. I removed it.

The Linker/Input/Additional Dependencies list is indeed set up to point to Release (or Debug). It does that, because that is where the LLVM build automatically sticks the relevant .lib files that are a dependency for Cone's use of LLVM. I am not sure why you would want to put them somewhere else. I don't see a trailing backslash here, though, so maybe you are not referring to this.

I don't believe LLVM 7 automatically builds the WebAssembly target (though later releases do). So when you build LLVM 7, you will have to configure CMake via an option to ask for the WebAssembly target to be generated (LLVM_EXPERIMENTAL_TARGETS_TO_BUILD set to WebAssembly). 

LLVM on Windows is a royal pain, because it requires that you specifically name all the .libs you want to link in. And if your compiler supports all its targets (as Cone does), you have to have them all listed in the Project file, and all correct, and of course this list changes from one LLVM release to another. `LLVMAVRAsmParser.lib` is one such for the AVR target. `LLVMX86AsmPrinter.lib` is another for the x86 target, which likely you will need. You will also find .lib for WebAssembly (e.g., `LLVMWebAssemblyInfo.lib`. Again, LLVM changes this list from release to release, necessitating changes to the project file on Windows. So feel free to adjust this list of .libs to match what you end up building with LLVM. Even the LLVM devs have to do this with the Kaleidoscope example.

Again, good luck!

**Comment by pluckyporcupine** [comment]
Okay, I forgot to build LLVM in Release mode, so I was unable to build a Release build, but I think I have a working Debug build (it says that it compiled the two files in `test` successfully). It does not seem that LLVM copied all of the headers into the build folder, so I had to manually add the original source's header folder to get it to build because it couldn't find `llvm-c/Core.h` otherwise.

Building for x64 seems to have worked. I just had to add a release target and let Visual Studio generate the details.

> I am not sure why you would want to put them somewhere else. I don't see a trailing backslash here, though, so maybe you are not referring to this.

Based on different instructions, the structure of my LLVM 9.0.1 build was completely different. It was closer to an actual release build.

> So feel free to adjust this list of .libs to match what you end up building with LLVM.

I may try that in the future.

**Comment by jondgoodwin** [comment]
Congratulations. I am glad to hear you were successful in getting it to build and run.

Wrt the missing `llvm-c/Core.h`, the way I discovered to fix that is to perform not just the BUILD_ALL on LLVM, but also to run/build INSTALL. That copies over the needed include files etc.

Good luck playing with the compiler.
