### ISSUE TITLE
Error when compiling Hello World - example

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#26]
I successfully installed the current Cone on Ubuntu 20 (inside WSL2).

The following Hello World example:

```
import stdio

fn main():
  print <- "Hello world!"
```

runs fine within Cone's PlayGround, but when I try to compile it on my machine it errors out:

$ conec hello_world.cone
Error 1019: The name print does not refer to a declared name
 -->   print <- "Hello world!"
       ^--- hello_world.cone:4:3
Unsuccessful compile: 1 errors, 0 warnings

Is there any additional step I need to fix this? Thanks!

**Comment by jondgoodwin** [comment]
Congratulations on the successful install.

Sorry for the backward-incompatibility due to recent improvements to module handling. 

The reason it fails is because imports no longer automatically fold names into the current module's namespace. You have to ask for it:

import stdio::*

Or you should also be able to do:  stdio::print <- "Hello world!"

I hope this helps and fixes it for you.
