### ISSUE TITLE
Strange error in if expression using +=

### ISSUE THREAD

**Issue by Ivo-Balbaert** [jondgoodwin/cone#30]
This code 

```
fn main():
      mut a = 0
      if 42: a += 1
```

gives the Error 1048: This variable has not been initialized. There is no value to use. 
 -->
     ^--- test.cone:6:1
Unsuccessful compile: 1 errors, 0 warnings

However rewriting it as:  if 42: a = a + 1	
makes it work.

**Comment by jondgoodwin** [comment]
The opassign logic has been refactored to be easier to follow and safer.

It turns out several other bugs were also in play:
- A generation bug on intrinsic handling of double floats
- Bad logic in block type checking that pretended to inject a blockret, but didn't, causing block to misplace the lowered last expression (<-- the real reason for the reported bug)

All bugs have been fixed. Please close if you confirm this issue is now solved.

**Comment by Ivo-Balbaert** [comment]
Great, it works!
