### ISSUE TITLE
Automatic cast of index when using each

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#53]
`each i in 0 < N` should cast the 0 to the type of N when possible, because by default it is u32. So literals should be cast properly, as needed.

**Comment by jondgoodwin** [comment]
I understand why one might want this form of inference, but I suspect it is very unlikely to happen.

Although Cone does support bidirectional inference that allows it to resolve the type of untyped constants, with what are effectively operations, it does so from left to right. So, first it resolves 0 and then it checks whether N matches.

I have watched language designers try to create really complex inference rules for dealing with uncertainty "equally", and the rules get enormously tedious and fragile. This is too thorny a path, and I don't want to go down it.

That said, in the future I suspect that you will find it a lot easier to iterate over the collection directly, rather than iterate over the indices. So, this pattern will happen a lot less often than you are seeing now.

I would rather invest my time, near-term, in building a more versatile 'each' able to do that.
