### ISSUE TITLE
Literals with underscores not recognized by print and returns

### ISSUE THREAD

**Issue by git-yledu** [jondgoodwin/cone#57]
https://is.gd/GRNBmY

**Comment by Ivo-Balbaert** [comment]
Its the combination of _ and f that doesn't work. Perhaps they are not meant to be used together.

**Comment by jondgoodwin** [comment]
Good catch for you both.

The source of this bug is that I feed the string to C's function that converts a string to a float.  C does not accept underscores, so when it finds one, it stops and converts the number up to that.

This should not be that difficult to fix, but it will require building a new string from the old one before sending the number to C.

**Comment by jondgoodwin** [comment]
Fixed.
